version: '3.8'
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ".env.${APP_ENV}"
    # volumes:
      # - ./resources/sql/:/docker-entrypoint-initdb.d/
